### ISSUE TITLE
Server code

### ISSUE THREAD

**Issue by moosin** [ameenmaheen/SocialMentionAutoComplete#1]
Hi Ameen,
this is an awesome work 
can u please give the backend code in php 

Thank you

**Comment by ameenmaheen** [comment]
sorry man , That code was developed by someone else , sure you can get the code from INTERNET

**Comment by moosin** [comment]
Hi thanks for the replay 
if u don't mind can u give a sample json structure 

Thank you

**Comment by ameenmaheen** [comment]
That is given as MentionModel class
